### ISSUE TITLE
Code Check for Type Code in invoice and CreditNote seems to be wrong

### ISSUE THREAD

**Issue by AndreasPvd** [itplr-kosit/xrechnung-schematron#28]
According to the current schematron versions the same codes are valid for invoice an creditnote. This does not make sense, as there is a credit note that makes no sense e.g. with code 380 and an invoice, that makes no sense with the codes for the credit note...

**Comment by rkottmann** [comment]
Thanx for your feedback, You are commenting on decissions made by CEN. On the one hand they decided that there are own syntax for Invoices and CreditNotes and these codes to be put into these Syntaxes. 
I would qualify this as redundant by design.

Therefore, we will not fix it within the scope of XRechnung, but try to mirror your feedback in CEN.
