### ISSUE TITLE
Correction of patterns for line breaks in schematron implementation of BR-DE-18

### ISSUE THREAD

**Issue by mircokuhlmann** [itplr-kosit/xrechnung-schematron#5]
Currently, only two patterns are recognized. The following patterns must be accepted:

\r = CR (Carriage Return): Mac OS before X
\n = LF (Line Feed): Unix/Mac OS X
\r\n = CR + LF: Windows

Resulting in the reg-ex: (\r\n|\r|\n)

@fbuettner-hb Please confirm.

**Comment by fbuettner-hb** [comment]
Sounds fine to me. Since we use that regex for tokenizing, take care of priorities (simplified example):

count( tokenize('helloRNhallo','R|N|RN') )  => 3 (using Saxon)
count( tokenize('helloRNhallo','RN|R|N') )  => 2 (using Saxon)

Generally, regex alternatives are evaluated left-to-right. However, safest version is to explicitly add a negative look-ahead:

count( tokenize('helloRNhallo','R(?:N)|N|RN') ) => 2

**Comment by mircokuhlmann** [comment]
Using '\r(?:\n)|\n|\r\n' results in error: "capturing groups allowed only in XPath3.0"

Can we use an alternative expression?

Otherwise we use '(\r\n|\r|\n)'.

**Comment by mircokuhlmann** [comment]
Jour Fixe: If it cannot be resolved with @fbuettner-hb, we use '(\r\n|\r|\n)'. @rkottmann has clarified that regex alternatives are always evaluated left-to-right.

**Comment by fbuettner-hb** [comment]
okay - use (\r\n|\r|\n).

**Comment by mircokuhlmann** [comment]
Changes done for CII, UBL-Inv and UBL-CN.

**Comment by mircokuhlmann** [comment]
Next step: Testing.

Expected result: Line breaks in "Payment terms" (BT-20) should be respected in Windows, Mac and Linux machines.
